### ISSUE TITLE
Hand off navigation to default phone app

### ISSUE THREAD

**Issue by riccjohn** [Hangry-App/Hangry#23]
**Describe the solution you'd like**
Clicking on the 'navigate' button on top of a restaurant's card should open up the phone's default navigation map and bring you there

**Comment by aminoche** [comment]
This would be great... I think this is the next feature...but it looks complicated.

See this medium post: [react-native-maps](https://medium.com/@princessjanf/react-native-maps-with-direction-from-current-location-ab1a371732c2 )

**Comment by aminoche** [comment]
@riccjohn - I'll close this.
