### ISSUE TITLE
Feat: Change order of API requests

### ISSUE THREAD

**Issue by riccjohn** [Hangry-App/Hangry#84]
**Describe the solution you'd like**
- We should first make an API request to get a large number of restaurants that fit our cuisine criteria
- We'll then filter out any restaurants that don't have a menu, and grab the top X number of places that have menus
- Then, we'll get the price and rating of those restaurants and sort them
- Finally, we'll grab the menus for the places that we'll present to the user

**Comment by aminoche** [comment]
This is working now.
